### ISSUE TITLE
multithread ffmpeg run

### ISSUE THREAD

**Issue by kubriel** [GDquest/BPSProxy#10]
would be very nice to have multithreaded video processing in bpsproxy, so everything is much fasteron modern machines, especially when lot of media files in working directory.

**I'm submitting a...**

- [ ] Bug report.
- [x] Feature request.

## Bug report ##

**What is the current behavior?**

**What is the expected behavior?**

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

## Feature request ##

**Describe the problem you're trying to solve.**

**Tell us which solutions you've explored, the solution you would pick, and why you think it would be the best for everyone.**

## Other ##

**Other information**

**Comment by NathanLovato** [comment]
It's already multithreaded, with presets to use GPU encoding, optionally.
