### ISSUE TITLE
NVENC option on mobile GPU

### ISSUE THREAD

**Issue by dvsie** [GDquest/BPSProxy#4]
Hi. I have Windows 10, **bpsproxy-0.1.3**, Python.3.7_3.7.1264.0_x64. Notebook with Nvidia GT730M card. CUDA in blender 2.80 work fine. bpsproxy successfully work with cpu, but when use **-p nvenc** I see error.

_..so while type this msg I've search and find that **NVENC is hardware feature** and now I think that **-p nvenc** option not work for GTXXX and similar. And here is a GPU's _[matrix](https://developer.nvidia.com/video-encode-decode-gpu-support-matrix)_

Or may be I need configure ffmpeg or python somehow to use my GPU?

That's from cmd:
`C:\Users\User>python -m bpsproxy C:\Users\User\Desktop\test -s 25 50 100 -p nvenc

» Creating directories if necessary...

» Checking for existing proxies...
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.48s/file]

» Processing...
  0%|                                                                                          | 0/1 [00:00<?, ?file/s]Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\bpsproxy\__main__.py", line 142, in <module>
    main()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\bpsproxy\__main__.py", line 128, in main
    call(C, clargs, cmds=cmds, **kwargs)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\bpsproxy\call.py", line 75, in call
    return [p.stdout for p in ps]
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\bpsproxy\call.py", line 75, in <listcomp>
    return [p.stdout for p in ps]
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tqdm\std.py", line 1081, in __iter__
    for obj in iterable:
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\bpsproxy\call.py", line 72, in <lambda>
    ps = tqdm(map(lambda cmd: sp.run(cmd[1], **kwargs_s), cmds[1]),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ffmpeg', '-y', '-v', 'quiet', '-stats', '-i', 'C:\\Users\\User\\Desktop\\test\\IMG_0823.MOV', '-pix_fmt', 'yuv420p', '-g', '1', '-sn', '-an', '-vf', 'colormatrix=bt601:bt709', '-vf', 'scale=iw*0.25:ih*0.25', '-c:v', 'h264_nvenc', '-qp', '25', '-preset', 'fast', 'C:\\Users\\User\\Desktop\\test\\BL_proxy\\IMG_0823.MOV\\proxy_25.avi', '-pix_fmt', 'yuv420p', '-g', '1', '-sn', '-an', '-vf', 'colormatrix=bt601:bt709', '-vf', 'scale=iw*0.5:ih*0.5', '-c:v', 'h264_nvenc', '-qp', '25', '-preset', 'fast', 'C:\\Users\\User\\Desktop\\test\\BL_proxy\\IMG_0823.MOV\\proxy_50.avi', '-pix_fmt', 'yuv420p', '-g', '1', '-sn', '-an', '-vf', 'colormatrix=bt601:bt709', '-vf', 'scale=iw*1.0:ih*1.0', '-c:v', 'h264_nvenc', '-qp', '25', '-preset', 'fast', 'C:\\Users\\User\\Desktop\\test\\BL_proxy\\IMG_0823.MOV\\proxy_100.avi']' returned non-zero exit status 1.
  0%|                                                                                          | 0/1 [00:01<?, ?file/s]`

**Comment by dvsie** [comment]
> You have the h264 nvenc codec but I don't know why it's not working and the regular mp4 is.

So... Here is output cmd. After execute -vvv I have empty (0 bytes) file test\BL_proxy\IMG_0823.MOV\ **proxy_25.avi**
`
**C:\Users\User>python -m bpsproxy C:\Users\User\Desktop\test -s 25 -p nvenc -vvv**

INFO:BPS:WORKING-DIRECTORY :: C:\Users\User\Desktop\test
INFO:BPS:PRESET :: nvenc
INFO:BPS:SIZES :: [25]

» Creating directories if necessary...
INFO:BPS:Directory @ C:\Users\User\Desktop\test\BL_proxy\IMG_0823.MOV

» Checking for existing proxies...
DEBUG:BPS:CALL :: ffprobe -v error -select_streams v:0 -show_entries stream=nb_frames -of default=noprint_wrappers=1:nokey=1 C:\Users\User\Desktop\test\IMG_0823.MOV && ffprobe -v error -select_streams v:0 -show_entries stream=nb_frames -of default=noprint_wrappers=1:nokey=1 C:\Users\User\Desktop\test\BL_proxy\IMG_0823.MOV\proxy_25.avi
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.05file/s]

» Processing...
DEBUG:BPS:CALL :: ['ffmpeg', '-y', '-v', 'quiet', '-stats', '-i', 'C:\\Users\\User\\Desktop\\test\\IMG_0823.MOV', '-pix_fmt', 'yuv420p', '-g', '1', '-sn', '-an', '-vf', 'colormatrix=bt601:bt709', '-vf', 'scale=iw*0.25:ih*0.25', '-c:v', 'h264_nvenc', '-qp', '25', '-preset', 'fast', 'C:\\Users\\User\\Desktop\\test\\BL_proxy\\IMG_0823.MOV\\proxy_25.avi']
  0%|                                                                                          | 0/1 [00:00<?, ?file/s]Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\bpsproxy\__main__.py", line 142, in <module>
    main()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\bpsproxy\__main__.py", line 128, in main
    call(C, clargs, cmds=cmds, **kwargs)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\bpsproxy\call.py", line 75, in call
    return [p.stdout for p in ps]
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\bpsproxy\call.py", line 75, in <listcomp>
    return [p.stdout for p in ps]
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tqdm\std.py", line 1081, in __iter__
    for obj in iterable:
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\bpsproxy\call.py", line 72, in <lambda>
    ps = tqdm(map(lambda cmd: sp.run(cmd[1], **kwargs_s), cmds[1]),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ffmpeg', '-y', '-v', 'quiet', '-stats', '-i', 'C:\\Users\\User\\Desktop\\test\\IMG_0823.MOV', '-pix_fmt', 'yuv420p', '-g', '1', '-sn', '-an', '-vf', 'colormatrix=bt601:bt709', '-vf', 'scale=iw*0.25:ih*0.25', '-c:v', 'h264_nvenc', '-qp', '25', '-preset', 'fast', 'C:\\Users\\User\\Desktop\\test\\BL_proxy\\IMG_0823.MOV\\proxy_25.avi']' returned non-zero exit status 1.
  0%|
`

**Comment by NathanLovato** [comment]
It's the same as the previous report, it doesn't say anything. Can you run the command directly? `ffmpeg -y -v quiet -stats -i C:\Users\User\Desktop\test\IMG_0823.MOV -pix_fmt yuv420p -g 1 -sn -an -vf colormatrix=bt601:bt709 -vf scale=iw0.25:ih0.25 -c:v h264_nvenc -qp 25 -preset fast C:\Users\User\Desktop\test\BL_proxy\IMG_0823.MOV\proxy_25.avi`

**Comment by NathanLovato** [comment]
Note the folders must exist for the command to run

**Comment by dvsie** [comment]
`C:\Windows\system32>ffmpeg -y -v quiet -stats -i C:\Users\User\Desktop\test\IMG_0823.MOV -pix_fmt yuv420p -g 1 -sn -an -vf colormatrix=bt601:bt709 -vf scale=iw0.25:ih0.25 -c:v h264_nvenc -qp 25 -preset fast C:\Users\User\Desktop\test\BL_proxy\IMG_0823.MOV\proxy_25.avi

C:\Windows\system32>
`
nothing happens from user and from admin

**Comment by NathanLovato** [comment]
You need to run it without the quiet option: `ffmpeg -y -i C:\Users\User\Desktop\test\IMG_0823.MOV -pix_fmt yuv420p -g 1 -sn -an -vf colormatrix=bt601:bt709 -vf scale=iw0.25:ih0.25 -c:v h264_nvenc -qp 25 -preset fast C:\Users\User\Desktop\test\BL_proxy\IMG_0823.MOV\proxy_25.avi`

**Comment by dvsie** [comment]
Something new))
`C:\Users\User>ffmpeg -y -i C:\Users\User\Desktop\test\IMG_0823.MOV -pix_fmt yuv420p -g 1 -sn -an -vf colormatrix=bt601:bt709 -vf scale=iw0.25:ih0.25 -c:v h264_nvenc -qp 25 -preset fast C:\Users\User\Desktop\test\BL_proxy\IMG_0823.MOV\proxy_25.avi
ffmpeg version N-95004-g2f87c9f646 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20190918
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 35.100 / 56. 35.100
  libavcodec     58. 58.101 / 58. 58.101
  libavformat    58. 33.100 / 58. 33.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 58.102 /  7. 58.102
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\User\Desktop\test\IMG_0823.MOV':
  Metadata:
    major_brand     : qt
    minor_version   : 0
    compatible_brands: qt
    creation_time   : 2019-09-07T14:16:30.000000Z
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone SE
    com.apple.quicktime.software: 12.4
    com.apple.quicktime.creationdate: 2019-09-07T17:01:39+0300
  Duration: 00:00:32.13, start: 0.000000, bitrate: 18916 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc), 1920x1080, 18913 kb/s, 30 fps, 30 tbr, 600 tbn, 1200 tbc (default)
    Metadata:
      rotate          : 180
      creation_time   : 2019-09-07T14:16:30.000000Z
      handler_name    : Core Media Video
      encoder         : H.264
    Side data:
      displaymatrix: rotation of -180.00 degrees
Only '-vf scale=iw0.25:ih0.25' read, ignoring remaining -vf options: Use ',' to separate filters
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_nvenc))
Press [q] to stop, [?] for help
[Parsed_scale_0 @ 0000024641b5ec80] [Eval @ 0000007339bfe230] Undefined constant or missing '(' in 'iw0.25'
[Parsed_scale_0 @ 0000024641b5ec80] [Eval @ 0000007339bfe230] Undefined constant or missing '(' in 'ih0.25'
[Parsed_scale_0 @ 0000024641b5ec80] Error when evaluating the expression 'ih0.25'.
Maybe the expression for out_w:'iw0.25' or for out_h:'ih0.25' is self-referencing.
[Parsed_scale_0 @ 0000024641b5ec80] Failed to configure output pad on Parsed_scale_0
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0
Conversion failed!

C:\Users\User>`
![image](https://user-images.githubusercontent.com/55638332/65722846-ce847380-e0b5-11e9-8a91-b4968458dcd6.png)

**Comment by NathanLovato** [comment]
Weird, this might be a change in the very recent version of ffmpeg you're using. As you can see from the error report, the problem has to do with the scale size expressions. Try to use `-vf scale=iw*0.25:ih*0.25` instead of what you have

**Comment by dvsie** [comment]
>  Try to use -vf scale=iw*0.25:ih*0.25 instead of what you have

Need update driver for new API?
**C:\Users\User>ffmpeg -y -i C:\Users\User\Desktop\test\IMG_0823.MOV -pix_fmt yuv420p -g 1 -sn -an -vf colormatrix=bt601:bt709 -vf scale=iw*0.25:ih*0.25 -c:v h264_nvenc -qp 25 -preset fast C:\Users\User\Desktop\test\BL_proxy\IMG_0823.MOV\proxy_25.avi**
![image](https://user-images.githubusercontent.com/55638332/65809700-f43e7500-e1a8-11e9-944e-f67cd4aa11ce.png)

**Comment by NathanLovato** [comment]
Seems it's your GPU driver or your GPU, yes. This explains why bpsproxy only fails with nvenc. You will have to upgrade your driver or downgrade your version of ffmpeg.
