### ISSUE TITLE
Proxies lose video orientation

### ISSUE THREAD

**Issue by djibux** [GDquest/BPSProxy#7]
I'm submitting a…
- [x] Bug report.
- [ ] Feature request.

## Bug report ##
**What is the current behavior?**
I have videos with "Rotation" metadata (displayed using Exiftool).
The corresponding proxies do not have a "Rotation" metadata.
As a result, the proxy and the original video do not have the same orientation in blender (and in renderings).

**What is the expected behavior?**
Orientation metadata should be kept as is.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 
I guess I can share a video if that helps.

**Comment by NathanLovato** [comment]
If you have a short video clip I could use for testing, that'd definitely help. It's an issue I've never had, even using portrait videos from my phone.

**Comment by djibux** [comment]
I have created a small clip.  What's the best way to share it?

**Comment by NathanLovato** [comment]
You can drag and drop a zip archive here on github if it's small enough, otherwise, any file host  will do. If you don't want it to be available here send it to me via email at nathan [at] gdquest.com

**Comment by djibux** [comment]
Here is the sample:
[GH013094.zip](https://github.com/GDQuest/blender-proxies-generator/files/4231776/GH013094.zip)

The video was taken upside-down.  It is displayed properly in most video players but it needs to be transformed in blender to be displayed with the proper orientation.  The proxy is not upside-down.   I would expect both to have the same behavior in Blender.

Note that there is [a report](https://developer.blender.org/T58853) on the blender tracker reporting Blender ignoring metadata.  They do not consider it a bug:
> Reading more meta-data info would for sure be a nice to have feature, but that is absolutely not a bug…
Either way, I believe the proxy should be an exact copy of the initial video (except the resolution of course).

**Comment by NathanLovato** [comment]
There you go, the new release is up on pypi: `pip3 install --upgrade bpsproxy`

**Comment by djibux** [comment]
Awesome.  It works.  Thanks.

**Comment by NathanLovato** [comment]
You're welcome!
