### ISSUE TITLE
Is it usable now?

### ISSUE THREAD

**Issue by alikthename** [GDquest/BPSProxy#8]
The install instructions didn't work for me
pip install returned:
 Using cached https://files.pythonhosted.org/packages/36/91/66a1a8918566223204bf6b6ee6b81ede36f6bde021dd61c4ef9252d502c6/bpsproxy-0.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Oa0JY5/bpsproxy/setup.py", line 30, in <module>
        long_description=readme(),
      File "/tmp/pip-build-Oa0JY5/bpsproxy/setup.py", line 21, in readme
        with open("README.md") as f:
    IOError: [Errno 2] No such file or directory: 'README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Oa0JY5/bpsproxy/

But pip3 installed bpsproxy
but there is no bpsproxy app as it was described in  Readme
is the readme actual?
I'd like to try this proxy generation method
Thanks in advance

**Comment by NathanLovato** [comment]
It should work. Did you try installing it with python 3? You must use python 3.
Then the error about the readme is strange, I'll have to check. I have it installed from pip here myself and didn't have issues.

**Comment by NathanLovato** [comment]
I tried to install from pip and couldn't reproduce the issue.

Could you try the following commands:

```sh
# Update pip
python3 -m pip install --user --upgrade pip
```
Then
```sh
pip3 install bpsproxy
```

or

```sh
python3 -m pip install bpsproxy
```

If neither works, could you try

```sh
python --version
python3 --version
```

And share the versions with me?

**Comment by NathanLovato** [comment]
No reply, so I'll close for now. If this is still an issue please add a comment below, follow the instruction listed above, and I'll reopen the issue.
